export const PATH = {
  main: '/',
  login: '/login',
  signUp: '/signup',
  employees: '/employees',
  createEmployee: '/employees/createEmployee',
  createEmployeeAbs: 'createEmployee',
  profile: '/profile',
  userProfile: ':id/profile',
  employee: ':id',
  cvs: '/cvs',
  cv: ':cvId',
  createCV: '/cvs/createCV',
  createProject: '/projects/createProject',
  projects: '/projects',
  departments: '/departments',
  department: ':departmentId',
  createDepartment: '/departments/createDepartment',
  positions: '/positions',
  skills: '/skills',
  languages: '/languages',
  settings: '/settings',
};
